---

clean_up_image_tags:
  purge: true
  rotate: 7 days
  mini: 3

deploy_tokens:

  - name: gitlab-deploy-token
    username: ''
    expires_at: ''
    scopes:
      - read_registry

  - name: foo
    username: bar
    expires_at: ''
    scopes:
      - read_repository
      - read_registry

environments:

  - name: "*"
    protected: false
    masked: false
    variables:
      - BROWSER_PERFORMANCE_DISABLED: true
      - CODE_QUALITY_DISABLED: true
      - CODE_INTELLIGENCE_DISABLED: true
      - DAST_DISABLED: true
      - DEPENDENCY_SCANNING_DISABLED: true
      - LOAD_PERFORMANCE_DISABLED: true
      - PERFORMANCE_DISABLED: true
      - SAST_DISABLED: true
      - SECRET_DETECTION_DISABLED: true
      - TEST_DISABLED: true
      - MARIA_ENABLED: false
      - REDIS_ENABLED: true
      - ADDITIONAL_HOSTS: "your.ingress.domain"
      - DATABASE_URL: "mysql2://youre_db_username:your_db_password@your.db.host:3306/your_db_name"

  - name: "example-for-rails-app"
    protected: false
    masked: false
    variables:
      - DB_MIGRATE: RAILS_ENV=production bin/rails db:migrate
      - K8S_SECRET_MAIL_RECEIVER: value
      - K8S_SECRET_MAIL_DOMAIN: value
      - K8S_SECRET_MAIL_PASSWORD: value
      - K8S_SECRET_MAIL_PORT: value
      - K8S_SECRET_MAIL_SENDER: value
      - K8S_SECRET_MAIL_SERVER: value

  - name: "example-for-laravel-app"
    protected: false
    masked: false
    variables:
      - DB_INITIALIZE: php artisan migrate --force && php artisan db:seed --force
      - DB_MIGRATE: php artisan migrate --force && php artisan db:seed --force
      - K8S_SECRET_APP_DEBUG: false
      - K8S_SECRET_APP_KEY: base64:秘密
      - K8S_SECRET_APP_NAME: Test
      - K8S_SECRET_APP_ENV: value
      - K8S_SECRET_APP_URL: http://test
      - K8S_SECRET_LOG_CHANNEL: daily
      - K8S_SECRET_LOG_LEVEL: debug
      - K8S_SECRET_QUEUE_CONNECTION: database
      - K8S_SECRET_AUTH_CODE_HASH_SALT: '秘密'
      - K8S_SECRET_HASH_SALT: '秘密'
      - K8S_SECRET_REDIS_HOST: value
      - K8S_SECRET_REDIS_PASSWORD: value
      - K8S_SECRET_REDIS_PORT: 6379
      - K8S_SECRET_SESSION_DRIVER: value
      - K8S_SECRET_SESSION_LIFETIME: value
      - K8S_SECRET_QUEUE_CONNECTION: value
      - K8S_SECRET_MEDIA_DISK: value
      - K8S_SECRET_FILESYSTEM_DRIVER: value
      - K8S_SECRET_CACHE_DRIVER: value
      - K8S_SECRET_BROADCAST_DRIVER: value
