---

clean_up_image_tags:
  purge: true
  rotate: 7 days
  mini: 3

environments:

  - name: "*"
    protected: false
    masked: false
    variables:
      - CODE_QUALITY_DISABLED: true
      - CODE_INTELLIGENCE_DISABLED: true
      - PERFORMANCE_DISABLED: true
      - SAST_DISABLED: true
      - SECRET_DETECTION_DISABLED: true
      - TEST_DISABLED: true
      - MARIA_ENABLED: false

  - name: "production"
    protected: false
    masked: false
    variables:
      - ADDITIONAL_HOSTS: value1
      - DATABASE_URL: mysql2://value
      - key3: value3
      - key4: value4

  - name: "review/develop"
    protected: false
    masked: false
    variables:
      - ADDITIONAL_HOSTS: develop_value1
      - DATABASE_URL: value2
      - key3: value3
      - key4: value4
