---

clean_up_image_tags:
  purge: true
  rotate: 7 days
  mini: 3

environments:

  - name: "*"
    protected: false
    masked: false
    variables:
      - CODE_QUALITY_DISABLED: true
      - CODE_INTELLIGENCE_DISABLED: true
      - PERFORMANCE_DISABLED: true
      - SAST_DISABLED: true
      - SECRET_DETECTION_DISABLED: true
      - TEST_DISABLED: true
      - MARIA_ENABLED: false
      - REDIS_ENABLED: true
      - ADDITIONAL_HOSTS: "your.ingress.domain"
      - DATABASE_URL: "mysql2://youre_db_username:your_db_password@your.db.host:3306/your_db_name"
