environments:

  - name: "*"
    protected: false
    masked: false
    variables:
      - DB_MIGRATE: RAILS_ENV=production bin/rails db:migrate
      - K8S_SECRET_MAIL_RECEIVER: value
      - K8S_SECRET_MAIL_DOMAIN: value
      - K8S_SECRET_MAIL_PASSWORD: value
      - K8S_SECRET_MAIL_PORT: value
      - K8S_SECRET_MAIL_SENDER: value
      - K8S_SECRET_MAIL_SERVER: value
